### ISSUE TITLE
这个插件能自动检测出key么，如果不能，建议改成自定义key的方式，配合其他插件进行shiro回显利用

### ISSUE THREAD

**Issue by xDro1d** [0x141/ShiroRce-Burp#1]

**Comment by GitttttBottttt** [comment]
![image](https://user-images.githubusercontent.com/36138300/89432179-6261aa00-d773-11ea-9519-b418010ca192.png)
可以检测的噢

**Comment by xDro1d** [comment]
> ![image](https://user-images.githubusercontent.com/36138300/89432179-6261aa00-d773-11ea-9519-b418010ca192.png)
> 可以检测的噢

你截图这个用得是ShiroScan这个插件，不是ShiroRce-Burp吧

**Comment by n8v79a** [comment]
> _没有提供描述。_



> > ![图片](https://user-images.githubusercontent.com/36138300/89432179-6261aa00-d773-11ea-9519-b418010ca192.png)
> > 可以检测的噢
> 
> 你截图这个用得是ShiroScan这个插件，不是ShiroRce-Burp吧

有时间可以加个输入框，被动检测的不准备写。
